type MatchRule = {
  clue: string;
  pattern: RegExp;
  weight: number;
};

type SourceProfile = {
  domain: string;
  name: string;
  rules: MatchRule[];
};

type Evidence = {
  clue: string;
  excerpt: string;
  weight: number;
};

export type SourceCandidate = {
  domain: string;
  evidence: Evidence[];
  name: string;
  score: number;
};

export type SourceFlag = {
  label: string;
  severity: "low" | "medium" | "high";
};

export type SourceReport = {
  candidates: SourceCandidate[];
  flags: SourceFlag[];
  summary: string;
  suspicion: "low" | "medium" | "high";
};

const sourceProfiles: SourceProfile[] = [
  {
    name: "iLyricsHub",
    domain: "ilyricshub.com",
    rules: [
      { clue: "Mentions iLyricsHub directly", pattern: /\bilyricshub\b/i, weight: 12 },
      { clue: "Mentions Vijay Paul credit", pattern: /\bvijay paul\b/i, weight: 12 },
      {
        clue: "Uses common iLyricsHub article phrasing",
        pattern: /\boriginal lyrics of\b/i,
        weight: 6,
      },
      {
        clue: "Uses iLyricsHub-style explanation text",
        pattern: /\bmeaning of this song\b/i,
        weight: 4,
      },
    ],
  },
  {
    name: "Genius",
    domain: "genius.com",
    rules: [
      { clue: "Mentions Genius directly", pattern: /\bgenius\b/i, weight: 10 },
      { clue: "Contains 'You might also like'", pattern: /\byou might also like\b/i, weight: 8 },
      { clue: "Contains contributor metadata", pattern: /\bcontributors?\b/i, weight: 5 },
      { clue: "Contains embed prompt", pattern: /\bembed\b/i, weight: 4 },
      { clue: "Contains Romanized label", pattern: /\bromanized\b/i, weight: 6 },
    ],
  },
  {
    name: "AZLyrics",
    domain: "azlyrics.com",
    rules: [
      { clue: "Mentions AZLyrics directly", pattern: /\bazlyrics\b/i, weight: 10 },
      {
        clue: "Contains ringtone footer text",
        pattern: /\bsend\s+["']?.+["']?\s+ringtone to your cell\b/i,
        weight: 10,
      },
      {
        clue: "Contains correction footer text",
        pattern: /\bthanks to .+ for correcting these lyrics\b/i,
        weight: 10,
      },
      { clue: "Contains submit-corrections footer", pattern: /\bsubmit corrections\b/i, weight: 8 },
    ],
  },
  {
    name: "LyricsBell",
    domain: "lyricsbell.com",
    rules: [
      { clue: "Mentions LyricsBell directly", pattern: /\blyricsbell\b/i, weight: 10 },
      { clue: "Contains site domain", pattern: /\blyricsbell\.com\b/i, weight: 12 },
      { clue: "Contains promo footer phrasing", pattern: /\blatest lyrics\b/i, weight: 4 },
    ],
  },
  {
    name: "Lyricsraag",
    domain: "lyricsraag.com",
    rules: [
      { clue: "Mentions Lyricsraag directly", pattern: /\blyricsraag\b/i, weight: 10 },
      { clue: "Contains site domain", pattern: /\blyricsraag\.com\b/i, weight: 12 },
    ],
  },
  {
    name: "LyricsSawan",
    domain: "lyricssawan.com",
    rules: [
      { clue: "Mentions LyricsSawan directly", pattern: /\blyricssawan\b/i, weight: 10 },
      { clue: "Contains site domain", pattern: /\blyricssawan\.com\b/i, weight: 12 },
    ],
  },
  {
    name: "Lyrics.com",
    domain: "lyrics.com",
    rules: [
      { clue: "Mentions Lyrics.com directly", pattern: /\blyrics\.com\b/i, weight: 10 },
      {
        clue: "Contains licensed-and-provided phrasing",
        pattern: /\blyrics? licensed and provided by\b/i,
        weight: 8,
      },
    ],
  },
  {
    name: "LyricFind",
    domain: "lyricfind.com",
    rules: [
      { clue: "Mentions LyricFind directly", pattern: /\blyricfind\b/i, weight: 10 },
      { clue: "Contains LyricFind domain", pattern: /\blyricfind\.com\b/i, weight: 12 },
    ],
  },
];

const genericFlags: MatchRule[] = [
  {
    clue: "Contains an explicit lyrics-site URL or domain",
    pattern: /\b(?:https?:\/\/)?(?:www\.)?[a-z0-9-]+\.(?:com|in|net|org)\b/i,
    weight: 8,
  },
  {
    clue: "Contains article-style metadata",
    pattern: /\b(artist|album|released|producer|written by|movie|starring)\s*:/i,
    weight: 4,
  },
  {
    clue: "Contains share or promo footer text",
    pattern: /\b(share this song|share these lyrics|copy lyrics|follow us|read more)\b/i,
    weight: 5,
  },
  {
    clue: "Contains translation or transliteration labels",
    pattern: /\b(translation|translated by|romanized|english translation)\b/i,
    weight: 5,
  },
  {
    clue: "Contains AI-draft wording",
    pattern: /\b(ai draft|generated by ai|machine generated|auto-generated)\b/i,
    weight: 7,
  },
];

function collectEvidence(text: string, rules: MatchRule[]) {
  const evidence: Evidence[] = [];

  for (const rule of rules) {
    const match = text.match(rule.pattern);

    if (!match || !match[0]) {
      continue;
    }

    evidence.push({
      clue: rule.clue,
      excerpt: match[0].trim(),
      weight: rule.weight,
    });
  }

  return evidence;
}

function getSuspicionScore(flags: SourceFlag[], candidates: SourceCandidate[]) {
  const directSiteHit = candidates.some((candidate) => candidate.score >= 10);
  const strongSiteHit = candidates.some((candidate) => candidate.score >= 18);
  const highFlags = flags.filter((flag) => flag.severity === "high").length;
  const mediumFlags = flags.filter((flag) => flag.severity === "medium").length;

  if (strongSiteHit || highFlags >= 2) {
    return "high" as const;
  }

  if (directSiteHit || highFlags >= 1 || mediumFlags >= 2) {
    return "medium" as const;
  }

  return "low" as const;
}

export function detectSource(rawLyrics: string): SourceReport {
  const text = rawLyrics.replace(/\r\n?/g, "\n").trim();

  if (!text) {
    return {
      candidates: [],
      flags: [],
      summary: "Paste lyrics first to run a source check.",
      suspicion: "low",
    };
  }

  const candidates = sourceProfiles
    .map((profile) => {
      const evidence = collectEvidence(text, profile.rules);
      const score = evidence.reduce((total, item) => total + item.weight, 0);

      return {
        domain: profile.domain,
        evidence,
        name: profile.name,
        score,
      };
    })
    .filter((candidate) => candidate.score > 0)
    .sort((left, right) => right.score - left.score)
    .slice(0, 3);

  const flags = collectEvidence(text, genericFlags).map((item) => ({
    label: item.clue,
    severity:
      item.weight >= 7 ? ("high" as const) : item.weight >= 5 ? ("medium" as const) : ("low" as const),
  }));

  const suspicion = getSuspicionScore(flags, candidates);

  let summary = "No strong external-source fingerprints were detected.";

  if (candidates.length > 0) {
    summary = `Likely external-source match: ${candidates[0].name}. Review the clues before accepting the lyrics.`;
  } else if (flags.length > 0) {
    summary =
      "The text shows copy-paste warning signs, but there is not enough fingerprint data to name a specific site.";
  }

  return {
    candidates,
    flags,
    summary,
    suspicion,
  };
}
